// Generated by GitHub Copilot on 2025-10-19
using BlazorApp.Interfaces;
using BlazorApp.Models;
using Microsoft.Extensions.Logging;

namespace BlazorApp.Services;

public class EmailService(ILogger<EmailService> logger) : IEmailService
{
    private readonly ILogger<EmailService> _logger = logger;

    public async Task<bool> SendContactEmailAsync(ContactRequest contactRequest)
    {
        ArgumentNullException.ThrowIfNull(contactRequest);

        _logger.LogInformation(
            "Contact form submitted by {Name} ({Email}) regarding {EnquiryType} at {SubmittedAt}",
            contactRequest.Name,
            contactRequest.Email,
            contactRequest.EnquiryType,
            contactRequest.SubmittedAt);

        await Task.Delay(100);

        return true;
    }
}
