// Generated by GitHub Copilot on 2025-10-19
using BlazorApp.Models;

namespace BlazorApp.Interfaces;

public interface IEmailService
{
    Task<bool> SendContactEmailAsync(ContactRequest contactRequest);
}
