// Generated by GitHub Copilot on 2025-10-19
using System.ComponentModel.DataAnnotations;

namespace BlazorApp.Models;

public class ContactRequest
{
    [Required, MinLength(2)]
    public string Name { get; set; } = string.Empty;

    [Required, EmailAddress]
    public string Email { get; set; } = string.Empty;

    [Required, Phone]
    public string Mobile { get; set; } = string.Empty;

    [Url]
    public string? Website { get; set; }

    [Required]
    public string EnquiryType { get; set; } = string.Empty;

    [Required, MinLength(10)]
    public string Message { get; set; } = string.Empty;

    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;
}
